services:
  mongo:
    image: mongo:7.0
    container_name: wine-rental-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: wine-rental

volumes:
  mongo-data:
